### ISSUE TITLE
关于测试结果与论文不一致的问题

### ISSUE THREAD

**Issue by zhouxy2020** [adversarial-for-goodness/APF#1]
尊敬的zhang博士：
您好！
最近拜读了你的论文《Adversarial Privacy-preserving Filter》，并尝试运行了代码。
在运行代码的过程中有一些疑惑：
1、test.py文件中，设定了threshold=1.02，请问这个值是怎么确定的？
2、test.py文件中，最后以x_adv和ben计算accuracy，accuracy计算的是（prediction+1）中非零元素的个数。然而，仅当distance>0时，（prediction+1）才是非零。也就是说，当x_adv与ben之间的特征距离小于threshold时，accuracy才会增加。而在用你提供的模型及参数直接test时，wo_acc通常都小于0.01，这意味着大部分时候模型都将x_adv和ben视为不同人物，也就是说对模型的干扰不成功。这与你的论文所述偏差太大，请问是我在哪个地方理解错误了吗？
希望能得到您的回复，谢谢。

**Comment by jiamingzhang94** [comment]
1. 关于阈值问题是计算了LFW数据的best_threshold得到的，在此阈值下准确率最高，具体的参考代码https://github.com/luckycallor/InsightFace-tensorflow/blob/master/evaluate.py
2. 我觉得你理解可能有所偏差，x和ben是数据集中同一个人的一对图像，你可以show一下，所以不加对抗噪声的时候wo_acc是接近100%的，加了对抗噪声之后接近于0，才能说明干扰成功，也就是说人脸识别模型无法根据你的enrolled image识别出来你别的人脸图像。

**Comment by jiamingzhang94** [comment]
关于第二个问题，我好像get到你的点了，论文中使用的metric是进攻成功率（ASR），而代码中为了省事使用的是进攻后的准确率，这两个指标之间其实有一个换算关系 ASR=原始图像的准确率-对抗图像的准确率，原始图像的准确率LFW数据集大概是99.4%左右我记不太清了。所以论文中的ASR都是接近100%的值，而代码中的准确率是接近0%。

**Comment by zhouxy2020** [comment]
谢谢您的回复。
应该是我理解错了，文章中的ASR是dodging攻击成功率，我理解成impersonation了。
那么test.py中最后计算wo_acc时，把ben改成x会不会更直观一些呢。
